### PR TITLE
Create cookiecutter template for Xcode project

### PR DESCRIPTION
**Pull request by SamSchott**
This is the initial template commit, as discussed in https://github.com/beeware/briefcase/pull/525.

Regarding structure, I thought it best to keep this repo clean of any scripts to build the App-template. Instead, those can live in the dev branch of the `briefcase-macOS-app-template` repo and automatically create the Python version branches.

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
I've added a couple of minor tweaks, including Py3.9 compatibility, but otherwise this looks great!

**Comment by SamSchott** [comment]
I completely forgot to mention this, but you probably noticed during review anyways:

I snuck in a `--run-python` command line flag to just start a bare Python interpreter instead of the app module. This can be helpful for debugging a build (to step into the Python interpreter and manually check modules and paths). It could also be "abused" as a hook to create Python subprocesses, though the proper way of doing this would be to use `NSTask`.

**Comment by freakboy3742** [comment]
I did see the flag, and I assumed that it was for debugging purposes. I hadn't really considered it as an attack vector... but I guess it is. This particular vector has historically existed (since we shipped a raw python interpreter); and even with the new static binary, you could replace the contents of (say) `nslog.py` with something that opened an interactive session. So - I guess the question becomes whether the security benefit of making it a *little* more difficult to manufacture the attack vector is worth it. Thoughts?

**Comment by SamSchott** [comment]
I don't really have any experience with such security considerations but here is my take on it:

1. My understand was that modifying any of the resource files would invalidate the app signature. This should make attacks like modifying the contents of the Python lib or packages less likely. Providing a command line flag to start a bare Python interpreter would therefore provide an easier route.

2. You are right of course, the previous way of bundling a bare Python interpreter is similar. But why exactly would this be a problem? All the attacker gets is a Python interpreter - so they might just as well use the bundled system Python on macOS. Is the issue that the app bundle's interpreter identifies itself as a particular app and might therefore get access to specific resources, e.g., keychain passwords created by the app?

3. With the statically linked executable, it would be nice to preserve a way for Python libraries such as `multiprocessing` to still work. This was all well previously where `sys.executable` would still point to a bare interpreter. The flag was intended not only for debugging (though I used it just for that) but maybe also as a way to enable multiprocessing.

**Comment by freakboy3742** [comment]
I hadn't considered app signing; app signing should remove modification of `nslog.py` as a potential attack vector.

Your analysis about the Python interpreter is also solid AFAICT. My immediate reaction was based on avoiding the introduction of a new vector for arbitrary code execution - but as you note, a macOS box provides a Python interpreter out of the box, so that vector already exists on every macOS machine regardless of what we do.

Supporting multiprocessing would definitely be a nice-to-have (or a nice-to-restore) feature too. I *think* it should be possible to modify the Briefcase stub executable to look for `--multiprocessing-fork` as the first argument (and if it exists, start the interpreter as a multiprocessing subprocess) - but more investigation is required.

**Comment by SamSchott** [comment]
Regarding multiprocessing, yes, we'll have to carefully look at the multiprocessing code to see what they are doing.

Re security issues: the more I think about it, the more concerned I am. It's not so much the issue of arbitrary code execution but the problem of impersonating an app while doing so. Anything without admin privileges is already possible just from a shell or by using the system's Python interpreter. It becomes dangerous IMO when an app which is trusted by the user requests elevated privileges. For instance, if a user is presented with a message "Python would like to install a privileged helper tool", the end user will be very surprised and hesitant to approve. Getting this message from an app that the user has installed himself / herself and is actively using will appear more trustworthy.

**Comment by freakboy3742** [comment]
We definitely don't want to let arbitrary code masquerade as the user-space process is running; that has some pretty frightening security implications; on that basis, I'll purge the `--run-python` argument.

I also took a quick look at multiprocessing. The good news is that `fork`-based multiprocessing works out of the box with no modifications. `spawn`-based multiprocessing (which is the default start method for macOS multiprocessing as of 3.8) hits a wall, however. Code signing is the most immediate problem; macOS won't allow the import of the posix_shmem module until it is code signed; once it *is* signed, you hit the command line issue that you predicted.

After launching a couple of spawn-bombs in an attempt to see if there was a quick fix, I've determined there isn't one :-) That's doesn't mean the fix is necessarily difficult - it just means it's not an obvious small patch. I'll open a ticket on briefcase to flag the fact that multiprocessing is problematic.

**Pull request merged**
